### ISSUE TITLE
Useless page

### ISSUE THREAD

**Issue by danielhuang** [havish10/rover-ruckus-scorer#1]
`/chicken` is a useless page and can be removed.

**Comment by HavishNetla** [comment]
no u

**Comment by danielhuang** [comment]
If you are expecting people to use your website, please try to act more professionally.

**Comment by HavishNetla** [comment]
https://www.youtube.com/watch?v=mMloc55o1jc <- has 87 million users and is worth 1.7 billion dollars

**Comment by danielhuang** [comment]
If you are going to act unprofessional in the name of large companies, please actually put some effort into it. One word and one letter comments will only cause people to look down upon you. I can edit your message!!!

**Comment by HavishNetla** [comment]
BTW for anyone reading this he made that page so... I am locking this thread

**Comment by havish10** [comment]
Closes: #1
